version: "3"

services:
  web:
    image: nginx:1.21.6-alpine
    ports:
      - 8000:80
    volumes:
      - ./app:/app:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
  php-app:
    image: php:7.1-fpm
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./app:/app:ro

  db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: db
      MYSQL_USER: php-app
      MYSQL_PASSWORD: password123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password123

volumes:
  db_data: {}
